### ISSUE TITLE
`Roadmap` link on the website leads to a 404 page

### ISSUE THREAD

**Issue by gshpychka** [Noovolari/leapp#183]
**Describe the bug**
![image](https://user-images.githubusercontent.com/23005347/138262928-51e03ff3-4b32-4dd6-85da-3f6dcbef7292.png)
The `Roadmap` link on the landing page leads to https://github.com/Noovolari/leapp/projects/4, which return a 404 page at the moment.

**To Reproduce**
1. Go to https://www.leapp.cloud/
2. Click on 'Roadmap'
3. See error

**Expected behavior**
Display the project's roadmap

**Comment by andreacavagna01** [comment]
Thanks :) we will replace it with [this discussion](https://github.com/Noovolari/leapp/discussions/178) for now, and we will provide a better open-source roadmap soon.

By now, the next steps are (not in the development order):
- [ ] Support multiple AWS Single Sign-On at the same time
- [ ] Support for GCP credentials
- [ ] Support for Alibaba Cloud Credentials
- [ ] Support for default browser authentication in AWS Single Sign-On
- [ ] Adding CLI for Leapp actions
- [ ] Support for AWS credentials process via Leapp CLI
